/* ---------------------------------------------------------------
   Exercise photographs.

   Two per exercise — the start of the movement and the end. The
   app alternates them, which is a truer demonstration than any
   drawing and costs nothing to play.

   From free-exercise-db, which is public domain. Regenerate with
   brand/match-exercises.mjs then brand/fetch-exercise-photos.mjs.
   This file is written by that second script — do not hand-edit.

   Some exercises are deliberately absent. The database has no honest
   picture of a wall sit, a bodyweight calf raise or a pike push-up,
   and the near-matches are a standing squat, a leg press machine and
   a handstand. Those screens fall back to a photograph of the muscle,
   which tells you less but does not tell you something untrue.
   brand/match-exercises.mjs lists them in NO_PHOTO.
   --------------------------------------------------------------- */
export const EXERCISE_FRAMES = {
  "Barbell Bench Press": [require('../assets/exercises/barbell-bench-press-0.jpg'), require('../assets/exercises/barbell-bench-press-1.jpg')],
  "Incline Dumbbell Press": [require('../assets/exercises/incline-dumbbell-press-0.jpg'), require('../assets/exercises/incline-dumbbell-press-1.jpg')],
  "Flat Dumbbell Press": [require('../assets/exercises/flat-dumbbell-press-0.jpg'), require('../assets/exercises/flat-dumbbell-press-1.jpg')],
  "Machine Chest Press": [require('../assets/exercises/machine-chest-press-0.jpg'), require('../assets/exercises/machine-chest-press-1.jpg')],
  "Push-up": [require('../assets/exercises/push-up-0.jpg'), require('../assets/exercises/push-up-1.jpg')],
  "Dips (chest lean)": [require('../assets/exercises/dips-chest-lean-0.jpg'), require('../assets/exercises/dips-chest-lean-1.jpg')],
  "Cable Fly": [require('../assets/exercises/cable-fly-0.jpg'), require('../assets/exercises/cable-fly-1.jpg')],
  "Dumbbell Fly": [require('../assets/exercises/dumbbell-fly-0.jpg'), require('../assets/exercises/dumbbell-fly-1.jpg')],
  "Pec Deck": [require('../assets/exercises/pec-deck-0.jpg'), require('../assets/exercises/pec-deck-1.jpg')],
  "Deadlift": [require('../assets/exercises/deadlift-0.jpg'), require('../assets/exercises/deadlift-1.jpg')],
  "Pull-up": [require('../assets/exercises/pull-up-0.jpg'), require('../assets/exercises/pull-up-1.jpg')],
  "Lat Pulldown": [require('../assets/exercises/lat-pulldown-0.jpg'), require('../assets/exercises/lat-pulldown-1.jpg')],
  "Barbell Row": [require('../assets/exercises/barbell-row-0.jpg'), require('../assets/exercises/barbell-row-1.jpg')],
  "Chest-Supported Row": [require('../assets/exercises/chest-supported-row-0.jpg'), require('../assets/exercises/chest-supported-row-1.jpg')],
  "Single-Arm Dumbbell Row": [require('../assets/exercises/single-arm-dumbbell-row-0.jpg'), require('../assets/exercises/single-arm-dumbbell-row-1.jpg')],
  "Seated Cable Row": [require('../assets/exercises/seated-cable-row-0.jpg'), require('../assets/exercises/seated-cable-row-1.jpg')],
  "Straight-Arm Pulldown": [require('../assets/exercises/straight-arm-pulldown-0.jpg'), require('../assets/exercises/straight-arm-pulldown-1.jpg')],
  "Face Pull": [require('../assets/exercises/face-pull-0.jpg'), require('../assets/exercises/face-pull-1.jpg')],
  "Inverted Row": [require('../assets/exercises/inverted-row-0.jpg'), require('../assets/exercises/inverted-row-1.jpg')],
  "Overhead Press": [require('../assets/exercises/overhead-press-0.jpg'), require('../assets/exercises/overhead-press-1.jpg')],
  "Seated Dumbbell Press": [require('../assets/exercises/seated-dumbbell-press-0.jpg'), require('../assets/exercises/seated-dumbbell-press-1.jpg')],
  "Arnold Press": [require('../assets/exercises/arnold-press-0.jpg'), require('../assets/exercises/arnold-press-1.jpg')],
  "Machine Shoulder Press": [require('../assets/exercises/machine-shoulder-press-0.jpg'), require('../assets/exercises/machine-shoulder-press-1.jpg')],
  "Lateral Raise": [require('../assets/exercises/lateral-raise-0.jpg'), require('../assets/exercises/lateral-raise-1.jpg')],
  "Cable Lateral Raise": [require('../assets/exercises/cable-lateral-raise-0.jpg'), require('../assets/exercises/cable-lateral-raise-1.jpg')],
  "Rear Delt Fly": [require('../assets/exercises/rear-delt-fly-0.jpg'), require('../assets/exercises/rear-delt-fly-1.jpg')],
  "Barbell Curl": [require('../assets/exercises/barbell-curl-0.jpg'), require('../assets/exercises/barbell-curl-1.jpg')],
  "Dumbbell Curl": [require('../assets/exercises/dumbbell-curl-0.jpg'), require('../assets/exercises/dumbbell-curl-1.jpg')],
  "Hammer Curl": [require('../assets/exercises/hammer-curl-0.jpg'), require('../assets/exercises/hammer-curl-1.jpg')],
  "Incline Dumbbell Curl": [require('../assets/exercises/incline-dumbbell-curl-0.jpg'), require('../assets/exercises/incline-dumbbell-curl-1.jpg')],
  "Cable Curl": [require('../assets/exercises/cable-curl-0.jpg'), require('../assets/exercises/cable-curl-1.jpg')],
  "Chin-up": [require('../assets/exercises/chin-up-0.jpg'), require('../assets/exercises/chin-up-1.jpg')],
  "Close-Grip Bench Press": [require('../assets/exercises/close-grip-bench-press-0.jpg'), require('../assets/exercises/close-grip-bench-press-1.jpg')],
  "Triceps Rope Pushdown": [require('../assets/exercises/triceps-rope-pushdown-0.jpg'), require('../assets/exercises/triceps-rope-pushdown-1.jpg')],
  "Overhead Cable Extension": [require('../assets/exercises/overhead-cable-extension-0.jpg'), require('../assets/exercises/overhead-cable-extension-1.jpg')],
  "Skull Crusher": [require('../assets/exercises/skull-crusher-0.jpg'), require('../assets/exercises/skull-crusher-1.jpg')],
  "Dumbbell Kickback": [require('../assets/exercises/dumbbell-kickback-0.jpg'), require('../assets/exercises/dumbbell-kickback-1.jpg')],
  "Bench Dip": [require('../assets/exercises/bench-dip-0.jpg'), require('../assets/exercises/bench-dip-1.jpg')],
  "Back Squat": [require('../assets/exercises/back-squat-0.jpg'), require('../assets/exercises/back-squat-1.jpg')],
  "Front Squat": [require('../assets/exercises/front-squat-0.jpg'), require('../assets/exercises/front-squat-1.jpg')],
  "Leg Press": [require('../assets/exercises/leg-press-0.jpg'), require('../assets/exercises/leg-press-1.jpg')],
  "Goblet Squat": [require('../assets/exercises/goblet-squat-0.jpg'), require('../assets/exercises/goblet-squat-1.jpg')],
  "Bulgarian Split Squat": [require('../assets/exercises/bulgarian-split-squat-0.jpg'), require('../assets/exercises/bulgarian-split-squat-1.jpg')],
  "Walking Lunge": [require('../assets/exercises/walking-lunge-0.jpg'), require('../assets/exercises/walking-lunge-1.jpg')],
  "Leg Extension": [require('../assets/exercises/leg-extension-0.jpg'), require('../assets/exercises/leg-extension-1.jpg')],
  "Bodyweight Squat": [require('../assets/exercises/bodyweight-squat-0.jpg'), require('../assets/exercises/bodyweight-squat-1.jpg')],
  "Romanian Deadlift": [require('../assets/exercises/romanian-deadlift-0.jpg'), require('../assets/exercises/romanian-deadlift-1.jpg')],
  "Dumbbell RDL": [require('../assets/exercises/dumbbell-rdl-0.jpg'), require('../assets/exercises/dumbbell-rdl-1.jpg')],
  "Lying Leg Curl": [require('../assets/exercises/lying-leg-curl-0.jpg'), require('../assets/exercises/lying-leg-curl-1.jpg')],
  "Seated Leg Curl": [require('../assets/exercises/seated-leg-curl-0.jpg'), require('../assets/exercises/seated-leg-curl-1.jpg')],
  "Good Morning": [require('../assets/exercises/good-morning-0.jpg'), require('../assets/exercises/good-morning-1.jpg')],
  "Nordic Curl": [require('../assets/exercises/nordic-curl-0.jpg'), require('../assets/exercises/nordic-curl-1.jpg')],
  "Hip Thrust": [require('../assets/exercises/hip-thrust-0.jpg'), require('../assets/exercises/hip-thrust-1.jpg')],
  "Glute Bridge": [require('../assets/exercises/glute-bridge-0.jpg'), require('../assets/exercises/glute-bridge-1.jpg')],
  "Sumo Deadlift": [require('../assets/exercises/sumo-deadlift-0.jpg'), require('../assets/exercises/sumo-deadlift-1.jpg')],
  "Step-up": [require('../assets/exercises/step-up-0.jpg'), require('../assets/exercises/step-up-1.jpg')],
  "Standing Calf Raise": [require('../assets/exercises/standing-calf-raise-0.jpg'), require('../assets/exercises/standing-calf-raise-1.jpg')],
  "Seated Calf Raise": [require('../assets/exercises/seated-calf-raise-0.jpg'), require('../assets/exercises/seated-calf-raise-1.jpg')],
  "Dumbbell Calf Raise": [require('../assets/exercises/dumbbell-calf-raise-0.jpg'), require('../assets/exercises/dumbbell-calf-raise-1.jpg')],
  "Hanging Knee Raise": [require('../assets/exercises/hanging-knee-raise-0.jpg'), require('../assets/exercises/hanging-knee-raise-1.jpg')],
  "Plank": [require('../assets/exercises/plank-0.jpg'), require('../assets/exercises/plank-1.jpg')],
  "Cable Crunch": [require('../assets/exercises/cable-crunch-0.jpg'), require('../assets/exercises/cable-crunch-1.jpg')],
  "Dead Bug": [require('../assets/exercises/dead-bug-0.jpg'), require('../assets/exercises/dead-bug-1.jpg')],
  "Russian Twist": [require('../assets/exercises/russian-twist-0.jpg'), require('../assets/exercises/russian-twist-1.jpg')],
  "Ab Wheel Rollout": [require('../assets/exercises/ab-wheel-rollout-0.jpg'), require('../assets/exercises/ab-wheel-rollout-1.jpg')],
  "Side Plank": [require('../assets/exercises/side-plank-0.jpg'), require('../assets/exercises/side-plank-1.jpg')],
  "Wide Push-up": [require('../assets/exercises/wide-push-up-0.jpg'), require('../assets/exercises/wide-push-up-1.jpg')],
  "Incline Push-up": [require('../assets/exercises/incline-push-up-0.jpg'), require('../assets/exercises/incline-push-up-1.jpg')],
  "Decline Push-up": [require('../assets/exercises/decline-push-up-0.jpg'), require('../assets/exercises/decline-push-up-1.jpg')],
  "Plyo Push-up": [require('../assets/exercises/plyo-push-up-0.jpg'), require('../assets/exercises/plyo-push-up-1.jpg')],
  "Superman": [require('../assets/exercises/superman-0.jpg'), require('../assets/exercises/superman-1.jpg')],
  "Wide-Grip Pull-up": [require('../assets/exercises/wide-grip-pull-up-0.jpg'), require('../assets/exercises/wide-grip-pull-up-1.jpg')],
  "Handstand Push-up": [require('../assets/exercises/handstand-push-up-0.jpg'), require('../assets/exercises/handstand-push-up-1.jpg')],
  "Seated Front Raise": [require('../assets/exercises/seated-front-raise-0.jpg'), require('../assets/exercises/seated-front-raise-1.jpg')],
  "Close-Grip Push-up": [require('../assets/exercises/close-grip-push-up-0.jpg'), require('../assets/exercises/close-grip-push-up-1.jpg')],
  "Triceps Dip": [require('../assets/exercises/triceps-dip-0.jpg'), require('../assets/exercises/triceps-dip-1.jpg')],
  "Jump Squat": [require('../assets/exercises/jump-squat-0.jpg'), require('../assets/exercises/jump-squat-1.jpg')],
  "Reverse Lunge": [require('../assets/exercises/reverse-lunge-0.jpg'), require('../assets/exercises/reverse-lunge-1.jpg')],
  "Single-Leg Glute Bridge": [require('../assets/exercises/single-leg-glute-bridge-0.jpg'), require('../assets/exercises/single-leg-glute-bridge-1.jpg')],
  "Flutter Kicks": [require('../assets/exercises/flutter-kicks-0.jpg'), require('../assets/exercises/flutter-kicks-1.jpg')],
  "Inchworm": [require('../assets/exercises/inchworm-0.jpg'), require('../assets/exercises/inchworm-1.jpg')],
  "Front Leg Raise": [require('../assets/exercises/front-leg-raise-0.jpg'), require('../assets/exercises/front-leg-raise-1.jpg')],
  "Air Bike": [require('../assets/exercises/air-bike-0.jpg'), require('../assets/exercises/air-bike-1.jpg')],
  "Cross-Body Crunch": [require('../assets/exercises/cross-body-crunch-0.jpg'), require('../assets/exercises/cross-body-crunch-1.jpg')],
  "Mountain Climber": [require('../assets/exercises/mountain-climber-0.jpg'), require('../assets/exercises/mountain-climber-1.jpg')],
  "Butt-Ups": [require('../assets/exercises/butt-ups-0.jpg'), require('../assets/exercises/butt-ups-1.jpg')],

  /* the women's side, and the period-pain sessions */
  "Barbell Glute Bridge": [require('../assets/exercises/barbell-glute-bridge-0.jpg'), require('../assets/exercises/barbell-glute-bridge-1.jpg')],
  "Butt Lift Bridge": [require('../assets/exercises/butt-lift-bridge-0.jpg'), require('../assets/exercises/butt-lift-bridge-1.jpg')],
  "Banded Hip Extension": [require('../assets/exercises/banded-hip-extension-0.jpg'), require('../assets/exercises/banded-hip-extension-1.jpg')],
  "Banded Hip Lift": [require('../assets/exercises/banded-hip-lift-0.jpg'), require('../assets/exercises/banded-hip-lift-1.jpg')],
  "Cable Glute Kickback": [require('../assets/exercises/cable-glute-kickback-0.jpg'), require('../assets/exercises/cable-glute-kickback-1.jpg')],
  "Rear Leg Raise": [require('../assets/exercises/rear-leg-raise-0.jpg'), require('../assets/exercises/rear-leg-raise-1.jpg')],
  "Lying Leg Lift": [require('../assets/exercises/lying-leg-lift-0.jpg'), require('../assets/exercises/lying-leg-lift-1.jpg')],
  "Kneeling Squat": [require('../assets/exercises/kneeling-squat-0.jpg'), require('../assets/exercises/kneeling-squat-1.jpg')],
  "Sumo Squat": [require('../assets/exercises/sumo-squat-0.jpg'), require('../assets/exercises/sumo-squat-1.jpg')],
  "Inner Thigh Machine": [require('../assets/exercises/inner-thigh-machine-0.jpg'), require('../assets/exercises/inner-thigh-machine-1.jpg')],
  "Outer Thigh Machine": [require('../assets/exercises/outer-thigh-machine-0.jpg'), require('../assets/exercises/outer-thigh-machine-1.jpg')],
  "Cable Hip Adduction": [require('../assets/exercises/cable-hip-adduction-0.jpg'), require('../assets/exercises/cable-hip-adduction-1.jpg')],
  "Banded Hip Adduction": [require('../assets/exercises/banded-hip-adduction-0.jpg'), require('../assets/exercises/banded-hip-adduction-1.jpg')],
  "Side Split Squat": [require('../assets/exercises/side-split-squat-0.jpg'), require('../assets/exercises/side-split-squat-1.jpg')],
  "Prone Hip Circles": [require('../assets/exercises/prone-hip-circles-0.jpg'), require('../assets/exercises/prone-hip-circles-1.jpg')],
  "Standing Hip Circles": [require('../assets/exercises/standing-hip-circles-0.jpg'), require('../assets/exercises/standing-hip-circles-1.jpg')],
  "Groiners": [require('../assets/exercises/groiners-0.jpg'), require('../assets/exercises/groiners-1.jpg')],
  "Calf Press": [require('../assets/exercises/calf-press-0.jpg'), require('../assets/exercises/calf-press-1.jpg')],
  "Donkey Calf Raise": [require('../assets/exercises/donkey-calf-raise-0.jpg'), require('../assets/exercises/donkey-calf-raise-1.jpg')],
  "Single-Leg Calf Raise": [require('../assets/exercises/single-leg-calf-raise-0.jpg'), require('../assets/exercises/single-leg-calf-raise-1.jpg')],
  "Banded Calf Raise": [require('../assets/exercises/banded-calf-raise-0.jpg'), require('../assets/exercises/banded-calf-raise-1.jpg')],
  "Chair Squat": [require('../assets/exercises/chair-squat-0.jpg'), require('../assets/exercises/chair-squat-1.jpg')],
  "Dumbbell Reverse Lunge": [require('../assets/exercises/dumbbell-reverse-lunge-0.jpg'), require('../assets/exercises/dumbbell-reverse-lunge-1.jpg')],
  "Bodyweight Walking Lunge": [require('../assets/exercises/bodyweight-walking-lunge-0.jpg'), require('../assets/exercises/bodyweight-walking-lunge-1.jpg')],
  "Banded Hamstring Curl": [require('../assets/exercises/banded-hamstring-curl-0.jpg'), require('../assets/exercises/banded-hamstring-curl-1.jpg')],
  "Floor Glute-Ham Raise": [require('../assets/exercises/floor-glute-ham-raise-0.jpg'), require('../assets/exercises/floor-glute-ham-raise-1.jpg')],
  "Scissor Kick": [require('../assets/exercises/scissor-kick-0.jpg'), require('../assets/exercises/scissor-kick-1.jpg')],
  "Bent-Knee Hip Raise": [require('../assets/exercises/bent-knee-hip-raise-0.jpg'), require('../assets/exercises/bent-knee-hip-raise-1.jpg')],
  "Leg Pull-In": [require('../assets/exercises/leg-pull-in-0.jpg'), require('../assets/exercises/leg-pull-in-1.jpg')],
  "Child’s Pose": [require('../assets/exercises/child-s-pose-0.jpg'), require('../assets/exercises/child-s-pose-1.jpg')],
  "Cat Cow": [require('../assets/exercises/cat-cow-0.jpg'), require('../assets/exercises/cat-cow-1.jpg')],
  "Pelvic Tilt Into Bridge": [require('../assets/exercises/pelvic-tilt-into-bridge-0.jpg'), require('../assets/exercises/pelvic-tilt-into-bridge-1.jpg')],
  "Standing Pelvic Tilt": [require('../assets/exercises/standing-pelvic-tilt-0.jpg'), require('../assets/exercises/standing-pelvic-tilt-1.jpg')],
  "One Knee To Chest": [require('../assets/exercises/one-knee-to-chest-0.jpg'), require('../assets/exercises/one-knee-to-chest-1.jpg')],
  "Reclined Butterfly": [require('../assets/exercises/reclined-butterfly-0.jpg'), require('../assets/exercises/reclined-butterfly-1.jpg')],
  "Side Lying Groin Stretch": [require('../assets/exercises/side-lying-groin-stretch-0.jpg'), require('../assets/exercises/side-lying-groin-stretch-1.jpg')],
  "Groin and Back Stretch": [require('../assets/exercises/groin-and-back-stretch-0.jpg'), require('../assets/exercises/groin-and-back-stretch-1.jpg')],
  "Seated Glute Stretch": [require('../assets/exercises/seated-glute-stretch-0.jpg'), require('../assets/exercises/seated-glute-stretch-1.jpg')],
  "Lying Glute Stretch": [require('../assets/exercises/lying-glute-stretch-0.jpg'), require('../assets/exercises/lying-glute-stretch-1.jpg')],
  "Supine Spinal Twist": [require('../assets/exercises/supine-spinal-twist-0.jpg'), require('../assets/exercises/supine-spinal-twist-1.jpg')],
  "Spinal Stretch": [require('../assets/exercises/spinal-stretch-0.jpg'), require('../assets/exercises/spinal-stretch-1.jpg')],
  "Lower Back Curl": [require('../assets/exercises/lower-back-curl-0.jpg'), require('../assets/exercises/lower-back-curl-1.jpg')],
  "Side-Lying Floor Stretch": [require('../assets/exercises/side-lying-floor-stretch-0.jpg'), require('../assets/exercises/side-lying-floor-stretch-1.jpg')],
  "Seated Hamstring Stretch": [require('../assets/exercises/seated-hamstring-stretch-0.jpg'), require('../assets/exercises/seated-hamstring-stretch-1.jpg')],
  "Leg-Up Hamstring Stretch": [require('../assets/exercises/leg-up-hamstring-stretch-0.jpg'), require('../assets/exercises/leg-up-hamstring-stretch-1.jpg')],
  "Standing Side Stretch": [require('../assets/exercises/standing-side-stretch-0.jpg'), require('../assets/exercises/standing-side-stretch-1.jpg')],
  "Overhead Stretch": [require('../assets/exercises/overhead-stretch-0.jpg'), require('../assets/exercises/overhead-stretch-1.jpg')],
  "Kneeling Hip Flexor Stretch": [require('../assets/exercises/kneeling-hip-flexor-stretch-0.jpg'), require('../assets/exercises/kneeling-hip-flexor-stretch-1.jpg')],
  "Middle Back Stretch": [require('../assets/exercises/middle-back-stretch-0.jpg'), require('../assets/exercises/middle-back-stretch-1.jpg')],
  "Upper Back Stretch": [require('../assets/exercises/upper-back-stretch-0.jpg'), require('../assets/exercises/upper-back-stretch-1.jpg')],
  "Chair Lower Back Stretch": [require('../assets/exercises/chair-lower-back-stretch-0.jpg'), require('../assets/exercises/chair-lower-back-stretch-1.jpg')],
  "Quad Stretch": [require('../assets/exercises/quad-stretch-0.jpg'), require('../assets/exercises/quad-stretch-1.jpg')],
  "Glute Kickback": [require('../assets/exercises/glute-kickback-0.jpg'), require('../assets/exercises/glute-kickback-1.jpg')],
  "Floor Back Extension": [require('../assets/exercises/floor-back-extension-0.jpg'), require('../assets/exercises/floor-back-extension-1.jpg')],
  "Band Pull Apart": [require('../assets/exercises/band-pull-apart-0.jpg'), require('../assets/exercises/band-pull-apart-1.jpg')],
  "Banded Rear Fly": [require('../assets/exercises/banded-rear-fly-0.jpg'), require('../assets/exercises/banded-rear-fly-1.jpg')],
  "Banded Upright Row": [require('../assets/exercises/banded-upright-row-0.jpg'), require('../assets/exercises/banded-upright-row-1.jpg')],
  "Self-Resisted Curl": [require('../assets/exercises/self-resisted-curl-0.jpg'), require('../assets/exercises/self-resisted-curl-1.jpg')],
  "Banded Shoulder Press": [require('../assets/exercises/banded-shoulder-press-0.jpg'), require('../assets/exercises/banded-shoulder-press-1.jpg')],
  "Banded Lateral Raise": [require('../assets/exercises/banded-lateral-raise-0.jpg'), require('../assets/exercises/banded-lateral-raise-1.jpg')],
  "Banded Chest Fly": [require('../assets/exercises/banded-chest-fly-0.jpg'), require('../assets/exercises/banded-chest-fly-1.jpg')],
  "Banded Triceps Extension": [require('../assets/exercises/banded-triceps-extension-0.jpg'), require('../assets/exercises/banded-triceps-extension-1.jpg')],
  "Banded Squat": [require('../assets/exercises/banded-squat-0.jpg'), require('../assets/exercises/banded-squat-1.jpg')],
  "Banded Good Morning": [require('../assets/exercises/banded-good-morning-0.jpg'), require('../assets/exercises/banded-good-morning-1.jpg')],
  "Monster Walk": [require('../assets/exercises/monster-walk-0.jpg'), require('../assets/exercises/monster-walk-1.jpg')],
};

export function framesFor(exercise) {
  const n = exercise && (exercise.n || exercise.name);
  return EXERCISE_FRAMES[n] || null;
}
